SELECT t.TABLE_NAME
		,c.COLUMN_NAME 
FROM INFORMATION_SCHEMA.TABLES t 
INNER JOIN INFORMATION_SCHEMA.COLUMNS c ON t.TABLE_NAME = c.TABLE_NAME
WHERE t.TABLE_SCHEMA = 'rally_stats'
AND c.COLUMN_NAME LIKE '%ID'
AND c.EXTRA = 'auto_increment'